name: celebrated
description: Birthdays reminder,planner and gift sharing app for  individuals and organizations.
publish_to: 'none'
version: 1.0.1+4
environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.13
  get: ^4.6.5
  google_fonts: ^3.0.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  image_fade: ^0.6.1
  auth_buttons: ^1.0.1+4
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.6
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.4
  permission_handler: ^10.2.0
  share_plus: ^6.2.0
  date_time_picker: ^2.1.0
  flutter_countdown_timer: ^4.1.0
  contextmenu: ^3.0.0
  lit_relative_date_time: ^1.2.0
  google_sign_in: ^5.3.3
  url_launcher: ^6.1.4
#  pricing_cards: ^0.0.7
  phone_form_field: ^7.0.2
  cloud_functions: ^4.0.4
  pricing_cards: ^0.0.7
  flutter_stripe: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/logos/b-remind-logo-1024.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/logos/b-remind-logo-1024.png"
  adaptive_icon_background: "#fcc21b"
  web:
    generate: true
    image_path: "assets/logos/b-remind-logo-1024.png"
    background_color: "#FFFFFF"
    theme_color: "#fcc21b"


flutter_native_splash:
  color: "#ffffff"
  image: "assets/logos/b-remind-logo-1024.png"


flutter:
  uses-material-design: true
  assets:
    - assets/intro/
    - assets/defualt_icons/
    - assets/logos/
