// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwRh6Kr-VWNhXQzILU_T1N0KhEWJ0V94U',
    appId: '1:651776985530:web:be7325660ded1a6a173583',
    messagingSenderId: '651776985530',
    projectId: 'breminderapp',
    authDomain: 'breminderapp.firebaseapp.com',
    storageBucket: 'breminderapp.appspot.com',
    measurementId: 'G-BDEM5ZB7W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSdMJsDl8zJONkwGqQlbC7XRgitBpa4E',
    appId: '1:651776985530:android:c85c47ae97e8ba92173583',
    messagingSenderId: '651776985530',
    projectId: 'breminderapp',
    storageBucket: 'breminderapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJkPXzmWdBFoR-9fwWQFoB7peV4nNEiY',
    appId: '1:651776985530:ios:8794e6a901f251c8173583',
    messagingSenderId: '651776985530',
    projectId: 'breminderapp',
    storageBucket: 'breminderapp.appspot.com',
    iosClientId: '651776985530-vf9h68tretevaim8cjs4u0ir40dv4cqr.apps.googleusercontent.com',
    iosBundleId: 'com.bremind.bremind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJkPXzmWdBFoR-9fwWQFoB7peV4nNEiY',
    appId: '1:651776985530:ios:8794e6a901f251c8173583',
    messagingSenderId: '651776985530',
    projectId: 'breminderapp',
    storageBucket: 'breminderapp.appspot.com',
    iosClientId: '651776985530-vf9h68tretevaim8cjs4u0ir40dv4cqr.apps.googleusercontent.com',
    iosBundleId: 'com.bremind.bremind',
  );
}
