// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1qdDH3YEFoI2IUw1IyUr9S9gD3uLJIc',
    appId: '1:690288905141:web:09d60e34268561d50be7fc',
    messagingSenderId: '690288905141',
    projectId: 'celebrated-app',
    authDomain: 'celebrated-app.firebaseapp.com',
    storageBucket: 'celebrated-app.appspot.com',
    measurementId: 'G-QCL58Y84K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5f8YyfmEew5Ls_2d0g5_pMNPhtPrPL8',
    appId: '1:690288905141:android:d0cff77c4fee70fa0be7fc',
    messagingSenderId: '690288905141',
    projectId: 'celebrated-app',
    storageBucket: 'celebrated-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPuWkw9Dlig7yBZAkqkELaXue2FQmQaag',
    appId: '1:690288905141:ios:206ef527105576c50be7fc',
    messagingSenderId: '690288905141',
    projectId: 'celebrated-app',
    storageBucket: 'celebrated-app.appspot.com',
    iosClientId: '690288905141-21qb4stvboau0oe29l59anne9u50rv41.apps.googleusercontent.com',
    iosBundleId: 'com.rodrickvy.celebrated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPuWkw9Dlig7yBZAkqkELaXue2FQmQaag',
    appId: '1:690288905141:ios:233e10f01a6c46ee0be7fc',
    messagingSenderId: '690288905141',
    projectId: 'celebrated-app',
    storageBucket: 'celebrated-app.appspot.com',
    iosClientId: '690288905141-4e2rfca8pqo9dt18hlb5bb130nbn8nsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.celebrated',
  );
}
