// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgBcYmi5SFNUNDxm88IqtcFrKUdqM1bc',
    appId: '1:144465290198:web:8fd36c7799c4ded6d57a77',
    messagingSenderId: '144465290198',
    projectId: 'letstalk-1',
    authDomain: 'letstalk-1.firebaseapp.com',
    databaseURL: 'https://letstalk-1.firebaseio.com',
    storageBucket: 'letstalk-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCssvmvwEHOKQa70pMEubaeU4vQ12G-QlY',
    appId: '1:144465290198:android:d0909a597c41962ad57a77',
    messagingSenderId: '144465290198',
    projectId: 'letstalk-1',
    databaseURL: 'https://letstalk-1.firebaseio.com',
    storageBucket: 'letstalk-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE38MC2HyUpgYpLMQ2SH7YFOfd5pEyMZ8',
    appId: '1:144465290198:ios:ed359266ad0e6b8cd57a77',
    messagingSenderId: '144465290198',
    projectId: 'letstalk-1',
    databaseURL: 'https://letstalk-1.firebaseio.com',
    storageBucket: 'letstalk-1.appspot.com',
    iosClientId: '144465290198-9rptca93k44cm9umnthj0m4pi73jj6ub.apps.googleusercontent.com',
    iosBundleId: 'com.rudo.bereminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE38MC2HyUpgYpLMQ2SH7YFOfd5pEyMZ8',
    appId: '1:144465290198:ios:ed359266ad0e6b8cd57a77',
    messagingSenderId: '144465290198',
    projectId: 'letstalk-1',
    databaseURL: 'https://letstalk-1.firebaseio.com',
    storageBucket: 'letstalk-1.appspot.com',
    iosClientId: '144465290198-9rptca93k44cm9umnthj0m4pi73jj6ub.apps.googleusercontent.com',
    iosBundleId: 'com.rudo.bereminder',
  );
}
